### ISSUE TITLE
Impossible to generate a DSK with a midi music file for CPC

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#526]
With the standard canyon.mid file, I tried the following code : 
``fugue = LOAD MUSIC("canyon.mid")
MUSIC fugue: MUSIC VOLUME MAX VOLUME: MUSIC TEMPO 35``

With ugBasic IDE when I compile I got no errors, but when I try to run the emulator, it says : 
![image](https://user-images.githubusercontent.com/118670680/204107566-3cb0a668-e779-4387-8031-ff55e8d1f8b6.png)

**Comment by spotlessmind1975** [comment]
Trying to repeat the anomaly, I noticed that the IDE compiler seems not to understand the fact that the compilation gave an error. The above program, if compiled on the command line, returns the following error:

    *** ERROR: syntax error, unexpected MUSIC, expecting end of file at 1 column 49 (49)

It would therefore seem more a problem of the IDE which, not realizing that the compilation has failed, launches the emulator anyway but with a non-existent disk. As soon as I fixed the IDE problem, this bug will actually be closed as the program doesn't seem syntactically correct to me. This should be the correct version, if I understand the intentions correctly (change the `TEMPO` of a music file is not supported, yet):

    fugue := LOAD MUSIC("examples/example.mid") 
    MUSIC fugue
    VOLUME VOLUME MAX

(ok, ok, I agree.... `VOLUME MAX` is not the best for a constant name! So maybe in the next release I find a syntactic alias)

**Comment by ldir-hector** [comment]
I tried this new source with no more success.

**Comment by spotlessmind1975** [comment]
Hello @ldir-hector and **thank you again for the feedback.** 

I used this one, with success:
https://github.com/spotlessmind1975/ugbasic/blob/main/examples/example.mid

Can you be kind enough to attach the MID file you use? 
Thank you!

**Comment by ldir-hector** [comment]
[canyon.zip](https://github.com/spotlessmind1975/ugbasic/files/10098108/canyon.zip)
Here it is, I zipped it to make it uploadable here.

**Comment by ldir-hector** [comment]
Well I still have the problem in ugBasic IDE, I shall try to compile it directly after lunch, I haven't installed the toolchains yet.

**Comment by spotlessmind1975** [comment]
Hello @ldir-hector, I fixed it with commit b7505115 and published an ugBASIC IDE coldfix fox `cpc` target.

Please try again, thank you!

**Comment by ldir-hector** [comment]
Well I still have the same problem, maybe it's a mirroring problem on itch.io. I don't know if I can check the revision of the version I dowloaded, I only know it is a 1.12, and itch.io still indicates that ugBASIC IDE hasn't since 13 days !

**Comment by ldir-hector** [comment]
I updated the compiler and saved as indicated but it stills failed to produce the DSK file ! I don't know what I am missing, I have rebooted my computer just in case...

**Comment by spotlessmind1975** [comment]
The problem was not related to either the IDE or the compiler, but to the MIDI management module. For a reason that escapes me, the compiler I set up to compile the executables for Windows cannot correctly detect the endianess of my machine. Which is why reading any MIDI with more than 255 bytes (or, alternatively, with many instruments / tracks / notes) resulted in a brutal crash of the executable - which the IDE confuses with correct execution, hence the bug.

The problem has been fixed but I am not entirely convinced that the music coming out for the canyon.mid file is what it is expected, so fine tuning is probably still needed.

I close anyway this bug.
