### ISSUE TITLE
Problem with RESOLUTION, ORIGIN and POINT AT

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#618]
I made this program : 

```
BITMAP ENABLE (160,200,16)
'RESOLUTION 640,400
CLS
'ORIGIN 0,400 UP

OPTION EXPLICIT
DEGREE
VAR angle AS FLOAT

VAR x AS INTEGER, y AS INTEGER

FOR angle = 0 TO 360
	x = (80+80*COS(angle))
	y = (100+100*SIN(angle))
	POINT AT (x,y)

NEXT

```
As long as I keep Resolution and Origin commented I got an oval. But if i uncomment them, I only got 1 pixel displayed.
I verified the Resolution and origin on this simple program : 
```
BITMAP ENABLE(160,200,16)
RESOLUTION 640,400
CLS 

ORIGIN 0,400 UP

DRAW 0,0 TO 80,100

```
and it works perfectly, so there might be a problem with point at.
I verified by using DRAW 80,100 TO x,y instead and I got a full oval as expected !

**Comment by spotlessmind1975** [comment]
Hi @ldir-hector, and **thank you for your bug report!**

I fixed it in COLDFIX v1.14 [rev. 20230624.1025]

I've done a close look at the problem, and I'm convinced that it is related to the implicit float-to-integer conversion that, once the variable's data type "barrier" is crossed, a lot of information is lost that can make `RESOLUTION` effective. As a result, `RESOLUTION`, which works on the principle of always being in integer mode, no longer works well. This also explains the different behavior between the various primitives (`DRAW` works by updating the coordinates, `POINT AT` doesn't).

To definitively solve the problem I converted the `RESOLUTION` algorithm from using integer variables to float ones. This determines, in addition to the release from the fact of being a precise multiple of the starting resolution, also the fact that the information is preserved and, therefore, it is now able to draw the circle (see below).

I point out that with this passage an improvement could be obtained by using `x` and `y` as `FLOAT`. 

As soon as possibile I will try it

![image](https://github.com/spotlessmind1975/ugbasic/assets/11718606/3fbcdc93-190c-496f-8b4e-eb3c204c545f)

**Comment by ldir-hector** [comment]
I think, there is still a problem, because I got this instead of a bigger circle : 
![image](https://github.com/spotlessmind1975/ugbasic/assets/118670680/3baa5c4f-3024-423a-9185-09a2ac70a5ae)
when I run this code : 

```
BITMAP ENABLE (160,200,16)
RESOLUTION 640,400
CLS
ORIGIN 0,400 UP

OPTION EXPLICIT
DEGREE
VAR angle AS FLOAT

VAR x AS FLOAT, y AS FLOAT

FOR angle = 0 TO 360
	x = (320+200*COS(angle))
	y = (200+200*SIN(angle))
	POINT AT (x,y)
NEXT
```

Maybe it's a problem with numbers superiors to 255 ?

**Comment by spotlessmind1975** [comment]
Hi @ldir-hector , first of all thank you again for the feedback and comments!

Actually I don't think there is a real error. It is just a side effect of a preventive optimization done by ugBASIC which, in some way, conflicts with the calculation. I'll try to explain the problem better. The ugBASIC's parser is of type LALRD (Look-Ahead, Left-to-right, Rightmost Derivation). This implies that it is not possible to infer the data type to the left before computing the data type to the right of an instruction.

Writing this expression:

    y = (200+200*SIN(angle))

ugBASIC parses it by degrading the `200` terms to simple `BYTE`, therefore with values (as you well guessed) reaching up to 255. The solution is to write all numbers with the float notation, which keeps the type homogeneous throughout the computation.

This is the result:
![image](https://github.com/spotlessmind1975/ugbasic/assets/11718606/86183f4c-210e-4a50-8960-effdcf44e259)

This is the source:

    BITMAP ENABLE (160,200,16)
    RESOLUTION 640,400
    CLS
    ORIGIN 0,400 UP

    OPTION EXPLICIT
    DEGREE
    VAR angle AS FLOAT

    VAR x AS FLOAT, y AS FLOAT

    FOR angle = 0 TO 360
    	x = (320.0+200.0*COS(angle))
    	y = (200.0+200.0*SIN(angle))
    	POINT AT (x,y)
    NEXT
